stages:
  - build
  - test
build-job:
  tags:
    - local
  script:
    - echo "Compiling code on my local Windows runner"
test_job:
  stage: test
  tags:
    - windows
  script:
    - echo "Test sur mon PC Windows 11"
    - echo "Pipeline exécuté localement avec GitLab Runner"

